server:
  port: 80

spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  thymeleaf:
    cache: false

beetl:
  templatesPath: templates
